<a href="https://colab.research.google.com/github/Aayan-Ahmed-17/Data_Science/blob/main/numpy_arr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Arrays


*   Creating arrays

*   Array reshaping

*   Mathematical operations

*   Matrix operations

*   Broadcasting

*   Filtering arrays

*   Random number generation

creation one dimension array and explore diff with py lists


In [ ]:

import numpy as np

arr = np.array([1,2,3,4])
py_list = [1,2,3,4]

print("arr===>", arr)
print("py_list===>", py_list)

arr===> [1 2 3 4]
py_list===> [1, 2, 3, 4]


Access Elements Using Indexing

In [ ]:
arr[2]
# print(arr[2])

3


Create Arrays of Zeros

In [16]:
np_zeros_arr = np.zeros((3,3))

"""output 3 rows and 3 cols with number zero"""
np_zeros_arr
# print(np_zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Create Arrays of Ones

In [18]:
np_ones_arr = np.ones((4,5))

"""output 4 rows and 5 cols with number one"""
np_ones_arr
# print(np_ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
